---

git_repo_location: https://bitbucket.org/opencast-community/matterhorn.git

mh_version: r/1.5.0

mvn_version: 3.1.1

mh_parent_dir: /opt/matterhorn
mh_base_dir: /opt/matterhorn/matterhorn
mh_work_dir: /opt/matterhorn/shared

admin_url: http://testadmin.usask.ca:8080
engage_url: http://testengage.usask.ca:8080

db_url: jdbc:mysql://testadmin.usask.ca/matterhorn
db_user: matterhorn
db_pass: matterhorn_db_passwd
db_ddl: false

is_ca: false

engage_solr_index: http://testadmin.usask.ca:8983

solr_port: 8983
solr_data_dir: /opt/matterhorn/apache-tomcat-7.0.5/solr
