---

- name: Install Git
  apt: pkg=git update_cache=yes state=present
  sudo: yes

- name: Install PCRE library
  apt: pkg=libpcre3-dev state=present
  sudo: yes

- name: Install OpenSSL development headers
  apt: pkg=libssl-dev state=present
  sudo: yes

- name: Install build tools
  apt: pkg=build-essential state=present
  sudo: yes

- name: Create MH parent dir
  file: path={{ mh_parent_dir }} owner="{{matterhorn_user}}" group="{{matterhorn_group}}" state=directory
  sudo: yes

- name: Fix MH parent dir permissions
  file: path={{mh_parent_dir}}/ owner="{{matterhorn_user}}" group="{{matterhorn_group}}" state=directory recurse=true
  sudo: true

- name: Checking if nginx binary exists
  stat: path={{mh_tools_dir}}/nginx/sbin/nginx
  register: nginxpresent

- name: Stopping nginx
  shell: killall nginx
  ignore_errors: yes
  sudo: yes

- name: Create streaming parent dir
  file: path={{mh_tools_dir}} owner="{{matterhorn_user}}" group="{{matterhorn_group}}" state=directory

- name: Create MH shared dir
  file: path={{mh_work_dir}} owner="{{matterhorn_user}}" group="{{matterhorn_group}}" state=directory

  #Mount NFS
- include: ../../common/tasks/nfs_mount.yml

- name: Create MH streams dir
  file: path={{mh_streaming_dir}} owner="{{matterhorn_user}}" group="{{matterhorn_group}}" state=directory

- name: Downloading nginx
  get_url: url=http://nginx.org/download/nginx-1.2.4.tar.gz
           dest={{mh_tools_dir}}/nginx-1.2.4.tar.gz
           force=no
           mode=0644

- name: Unzipping nginx
  shell: tar xzf nginx-1.2.4.tar.gz
         chdir={{mh_tools_dir}}
         creates=nginx-1.2.4

- name: Downloading RTMP module for nginx
  git: repo=https://github.com/arut/nginx-rtmp-module
       dest={{mh_tools_dir}}/nginx-rtmp-module
       update=yes
  when: inventory_hostname in groups['streamer']

- name: Preparing to build nginx
  shell: ./configure --prefix={{mh_tools_dir}}/nginx --pid-path=/var/run/nginx.pid
         chdir={{mh_tools_dir}}/nginx-1.2.4
  when: inventory_hostname not in groups['streamer']


- name: Preparing to build nginx with streaming components
  shell: ./configure --add-module={{mh_tools_dir}}/nginx-rtmp-module --prefix={{mh_tools_dir}}/nginx --pid-path=/var/run/nginx.pid
         chdir={{mh_tools_dir}}/nginx-1.2.4
  when: inventory_hostname in groups['streamer']

- name: Building nginx
  shell: make
         chdir={{mh_tools_dir}}/nginx-1.2.4

- name: Installing nginx
  shell: make install
         chdir={{mh_tools_dir}}/nginx-1.2.4

- name: Configuring nginx for http
  template: src=nginx-http.conf dest={{mh_tools_dir}}/nginx/conf/nginx.conf
  when: inventory_hostname not in groups['streamer']

- name: Configuring nginx for http and streaming
  template: src=nginx-streaming.conf dest={{mh_tools_dir}}/nginx/conf/nginx.conf
  when: inventory_hostname in groups['streamer']

- name: Configuring nginx init script
  template: src=nginx dest=/etc/init.d/nginx
  sudo: yes

- name: Fixing init script permissions
  shell: chmod a+x /etc/init.d/nginx
  sudo: yes

- name: Setting nginx to start on boot
  service: name=nginx state=started enabled=yes
  sudo: yes
