---

- name: Checking if ActiveMQ exists
  stat: path=/etc/init.d/activemq
  register: activemqpresent

- name: Stopping ActiveMQ
  service: name=activemq state=stopped
  sudo: yes
  when: activemqpresent.stat.exists is defined and activemqpresent.stat.exists == True
