---

- name: Checking if Matterhorn exists
  stat: path=/etc/init.d/matterhorn
  register: matterhornpresent

- name: Stopping Matterhorn
  service: name=matterhorn state=stopped
  sudo: yes
  when: matterhornpresent.stat.exists is defined and matterhornpresent.stat.exists == True
