---

  #Mount NFS
- include: ../../common/tasks/nfs_mount.yml

- name: Downloading Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.5-beta/bin/apache-tomcat-7.0.5.zip
           dest={{mh_parent_dir}}/apache-tomcat-7.0.5.zip
           force=no
           mode=0644

- name: Unzipping Tomcat
  shell: unzip apache-tomcat-7.0.5.zip
         chdir={{mh_parent_dir}}
         creates=apache-tomcat-7.0.5

- name: Downloading Solr
  get_url: url=http://archive.apache.org/dist/lucene/solr/1.4.1/apache-solr-1.4.1.zip
           dest={{mh_parent_dir}}/apache-solr-1.4.1.zip
           force=no
           mode=0644

- name: Unzipping Solr
  shell: unzip apache-solr-1.4.1.zip
         chdir={{mh_parent_dir}}
         creates=apache-solr-1.4.1

- name: Applying Solr to Tomcat
  shell: unzip apache-solr-1.4.1/example/webapps/solr.war -d apache-tomcat-7.0.5/webapps/solr
         chdir={{mh_parent_dir}}
         creates=apache-tomcat-7.0.5/webapps/solr

- name: Copying Engage search index
  shell: cp -rv {{mh_base_dir}}/modules/matterhorn-search-service-impl/src/main/resources/solr {{solr_data_dir}}
         chdir={{mh_parent_dir}}

- name: Creating lib directory
  shell: mkdir -p {{solr_data_dir}}/lib

- name: Copying required Solr jar
  shell: cp -rv {{mh_work_dir}}/.m2/repository/org/opencastproject/matterhorn-solr/{{mh_pom_version}}/matterhorn-solr-{{mh_pom_version}}.jar {{solr_data_dir}}/lib
         chdir={{mh_parent_dir}}

- name: Configure Tomcat
  template: src=server.xml dest={{mh_parent_dir}}/apache-tomcat-7.0.5/conf/

- name: Configure Solr
  template: src=solrconfig.xml dest={{solr_data_dir}}/conf/

- name: Fix file permissions
  shell: chmod 755 bin/*.sh
         chdir={{mh_parent_dir}}/apache-tomcat-7.0.5

- name: Symlinking Tomcat
  command: ln -s {{mh_parent_dir}}/apache-tomcat-7.0.5/bin/startup.sh /etc/init.d/solr
  sudo: yes

- name: Restarting Solr
  service: name=solr state=restarted
  sudo: yes
