---
# This playbook deploys a full Matterhorn cluster

- hosts: mysql
  user: "{{matterhorn_user}}"

  roles:
    - mysql-build
  vars_files:
    - group_vars/common.yml
    - group_vars/all-in-one.yml


- hosts: activemq
  user: "{{matterhorn_user}}"

  roles:
    - activemq-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: admin
  user: "{{matterhorn_user}}"

  roles:
    - matterhorn-base
    - matterhorn-core
    - admin-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/all-in-one.yml
    - roles/admin-build/vars/admin-all-in-one.yml


- hosts: streamer
  user: "{{matterhorn_user}}"

  roles:
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/all-in-one.yml


- hosts: solr
  user: "{{matterhorn_user}}"

  roles:
    - solr-build
  vars_files:
    - group_vars/common.yml
    - group_vars/all-in-one.yml


- hosts: engage
  user: "{{matterhorn_user}}"

  roles:
    - matterhorn-base
    - matterhorn-core
    - engage-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/all-in-one.yml
    - roles/engage-build/vars/engage-all-in-one.yml


- hosts: worker
  user: "{{matterhorn_user}}"

  roles:
    - matterhorn-base
    - matterhorn-core
    - worker-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/all-in-one.yml
    - roles/worker-build/vars/worker-all-in-one.yml


- hosts: capture
  user: "{{matterhorn_user}}"

  roles:
    - matterhorn-base
    - matterhorn-core
    - capture-agent-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/all-in-one.yml
    - roles/capture-agent-build/vars/capture-agent-all-in-one.yml
