---
# This playbook resets a full Matterhorn cluster

- include: stop.yml

- hosts: admin
  user: "{{matterhorn_user}}"

  roles:
    - matterhorn-clean
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - roles/admin-build/vars/admin.yml


- hosts: activemq
  user: "{{matterhorn_user}}"

  roles:
    - activemq-clean
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: solr
  user: "{{matterhorn_user}}"

  roles:
    - solr-clean
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: mysql
  user: "{{matterhorn_user}}"

  roles:
    - mysql-clean
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
