---
# This playbook deploys a full Matterhorn cluster

- hosts: fileserver
  user: "{{matterhorn_user}}"

  roles:
    - nfs-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: mysql
  user: "{{matterhorn_user}}"

  roles:
    - mysql-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: activemq
  user: "{{matterhorn_user}}"

  roles:
    - activemq-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: admin
  user: "{{matterhorn_user}}"

  roles:
    - maven
    - matterhorn-base
    - matterhorn-core
    - admin-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - roles/admin-build/vars/admin.yml


- hosts: streamer
  user: "{{matterhorn_user}}"

  roles:
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: solr
  user: "{{matterhorn_user}}"

  roles:
    - solr-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: engage
  user: "{{matterhorn_user}}"

  roles:
    - maven
    - matterhorn-base
    - matterhorn-core
    - node.js-build
    - engage-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - roles/engage-build/vars/engage.yml


- hosts: ingest
  user: "{{matterhorn_user}}"

  roles:
    - maven
    - matterhorn-base
    - matterhorn-core
    - ingest-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - roles/ingest-build/vars/ingest.yml


- hosts: worker
  user: "{{matterhorn_user}}"

  roles:
    - maven
    - ffmpeg
    - hunspell
    - sox
    - tesseract
    - matterhorn-base
    - matterhorn-core
    - worker-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - roles/worker-build/vars/worker.yml


- hosts: capture
  user: "{{matterhorn_user}}"

  roles:
    - pyca-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - group_vars/pyca.yml
