---
# This playbook deploys a full Matterhorn cluster

- hosts: fileserver
  user: matterhorn

  roles:
    - nfs-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: mysql
  user: matterhorn

  roles:
    - mysql-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: admin
  user: matterhorn

  roles:
    - matterhorn-base
    - matterhorn-core
    - admin-build
    - matterhorn-start
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - roles/admin-build/vars/admin.yml


- hosts: streamer
  user: matterhorn

  roles:
    - red5-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: solr
  user: matterhorn

  roles:
    - solr-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: engage
  user: matterhorn

  roles:
    - matterhorn-base
    - matterhorn-core
    - engage-build
    - matterhorn-start
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - roles/engage-build/vars/engage.yml


- hosts: ingest
  user: matterhorn

  roles:
    - matterhorn-base
    - matterhorn-core
    - ingest-build
    - matterhorn-start
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - roles/ingest-build/vars/ingest.yml


- hosts: worker
  user: matterhorn

  roles:
    - matterhorn-base
    - matterhorn-core
    - worker-build
    - matterhorn-start
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - roles/worker-build/vars/worker.yml


- hosts: capture
  user: matterhorn

  roles:
    - matterhorn-base
    - matterhorn-core
    - capture-agent-build
    - matterhorn-start
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - roles/capture-agent-build/vars/capture-agent.yml
