---
# This playbook starts a full Matterhorn cluster

- hosts: solr
  user: "{{matterhorn_user}}"

  roles:
    - solr-start
  vars_files:
    - group_vars/common.yml


- hosts: admin
  user: "{{matterhorn_user}}"

  roles:
    - matterhorn-start
  vars_files:
    - group_vars/common.yml


- hosts: matterhorn
  user: "{{matterhorn_user}}"

  roles:
    - matterhorn-start
  vars_files:
    - group_vars/common.yml

- hosts: capture
  user: "{{matterhorn_user}}"

  roles:
    - pyca-start
  vars_files:
    - group_vars/common.yml
