---
# This playbook stops a full Matterhorn cluster

- hosts: capture
  user: "{{matterhorn_user}}"

  roles:
    - pyca-start
  vars_files:
    - group_vars/common.yml

- hosts: matterhorn
  user: "{{matterhorn_user}}"

  roles:
    - matterhorn-stop
  vars_files:
    - group_vars/common.yml


- hosts: solr
  user: "{{matterhorn_user}}"

  roles:
    - solr-stop
  vars_files:
    - group_vars/common.yml

