---
# This playbook destroys a full Matterhorn cluster, data and binaries included

- include: stop.yml

- hosts: capture
  user: "{{matterhorn_user}}"

  roles:
    - pyca-wipe
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - group_vars/pyca.yml


- hosts: matterhorn
  user: "{{matterhorn_user}}"

  roles:
    - matterhorn-stop
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: activemq
  user: "{{matterhorn_user}}"

  roles:
    - activemq-wipe
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: solr
  user: "{{matterhorn_user}}"

  roles:
    - solr-wipe
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: mysql
  user: "{{matterhorn_user}}"

  roles:
    - mysql-wipe
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml

- hosts: all
  user: "{{matterhorn_user}}"

  roles:
    - nginx-wipe
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml

- hosts: all
  user: "{{matterhorn_user}}"

  roles:
    - matterhorn-wipe
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
