---

- name: Checking if Matterhorn exists
  stat: path=/etc/init.d/matterhorn
  register: matterhornpresent

- name: Install httplib2
  apt: pkg=python-httplib2 state=present
  when: matterhornpresent.stat.exists is defined and matterhornpresent.stat.exists == True
  sudo: yes

- name: Starting Matterhorn
  service: name=matterhorn state=started
  when: matterhornpresent.stat.exists is defined and matterhornpresent.stat.exists == True
  sudo: yes

- name: Waiting on Matterhorn to be available
  when: matterhornpresent.stat.exists is defined and matterhornpresent.stat.exists == True
  wait_for: port=8080

- name: Waiting until Matterhorn page contains `Opencast Video Capture Software` string
  when: matterhornpresent.stat.exists is defined and matterhornpresent.stat.exists == True
  uri: url=http://{{ inventory_hostname }} return_content=true
  register: response
  until: response.content is defined and response.content | search("Opencast Video Capture Software")
  delay: 10
  retries: 12

