---

- name: Checking if ActiveMQ exists
  stat: path=/etc/init.d/activemq
  register: activemqpresent

- name: Stop ActiveMQ
  service: name=activemq state=stopped enabled=no
  sudo: yes
  when: activemqpresent.stat.exists is defined and activemqpresent.stat.exists == True

- name: Removing ActiveMQ init script
  file: path=/etc/init.d/activemq state=absent
  sudo: yes
  when: activemqpresent.stat.exists is defined and activemqpresent.stat.exists == True

- name: Removing ActiveMQ global settings
  file: patch=/etc/default/activemq state=absent
  sudo: yes
  when: activemqpresent.stat.exists is defined and activemqpresent.stat.exists == True

- name: Wipe ActiveMQ root directory
  shell: rm -rf {{activemq_home_dir}}
  sudo: yes
