---

- include: ../../activemq-stop/tasks/main.yml

- name: Stop and disable ActiveMQ
  service: name=activemq state=stopped enabled=no
  sudo: yes
  when: activemqpresent.stat.exists is defined and activemqpresent.stat.exists == True

- name: Removing ActiveMQ init script
  file: path=/etc/init.d/activemq state=absent
  sudo: yes
  when: activemqpresent.stat.exists is defined and activemqpresent.stat.exists == True

- name: Removing ActiveMQ global settings
  file: path=/etc/default/activemq state=absent
  sudo: yes
  when: activemqpresent.stat.exists is defined and activemqpresent.stat.exists == True

- name: Wipe ActiveMQ root directory
  file: path={{activemq_home_dir}} state=absent
  sudo: yes
