---

- name: Loading platform variables
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: Umount NFS mount if mounted
  mount:
    name: "{{ oc_storage_dir }}"
    state: unmounted
  when: nfs_server is defined and 'fileserver' not in group_names and (handle_network_mounts | bool)
  become: yes

- import_tasks: debian.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- import_tasks: centos.yml
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"

- name: Remounting NFS mount if appropriate
  mount:
    name: "{{ oc_storage_dir }}"
    src: "{{ nfs_server }}:{{ oc_storage_dir }}"
    fstype: nfs
    state: mounted
    opts: "rw,sync,vers=3"
  become: yes
  when: nfs_server is defined and 'fileserver' not in group_names and (handle_network_mounts | bool)
