---

- include: ../../common/tasks/checkout_mh.yml

- name: Creating config directory
  file: src={{mh_base_dir}}/etc dest={{mh_config_dir}} state=link
  sudo: yes

- include: ../../common/tasks/clean_mh_logs.yml

- name: Fix logging directory permissions and linking
  file: src={{mh_log_dir}} dest={{mh_base_dir}}/logs owner={{matterhorn_user}} group={{matterhorn_group}} state=link
  sudo: true

- name: Configure init scripts
  template: src=etc-matterhorn-service.conf dest={{mh_base_dir}}/etc/service.conf

- name: Install the init scripts
  shell: install -p -D -m 0755 etc-init.d-matterhorn  /etc/init.d/matterhorn
         chdir={{mh_base_dir}}/docs/scripts/init/system/
  sudo: yes

- name: Install the system script
  shell: install -p -D -m 0755 usr-sbin-matterhorn    /usr/sbin/matterhorn
         chdir={{mh_base_dir}}/docs/scripts/init/system/
  sudo: yes

- name: Install the man-page
  shell: install -p -D -m 0644 matterhorn.8  /usr/share/man/man8 && rm -f matterhorn.8
         chdir={{mh_base_dir}}/docs/scripts/init/system/
  sudo: yes

- name: Configure config.properties
  template: src=config.properties dest={{mh_base_dir}}/etc/

- name: Configure organization profile
  template: src=org.opencastproject.organization-mh_default_org.cfg dest={{mh_base_dir}}/etc/load/

- name: Configure service registry
  template: src=org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImpl.properties dest={{mh_base_dir}}/etc/services/

- name: Set Matterhorn start on boot
  service: name=matterhorn enabled=yes
