---

- name: restart activemq
  action: service
    name=activemq
    state=restarted
  become: yes

- name: restart opencast
  action: service
    name=opencast
    state={{ build_ami | bool | ternary('stopped', 'restarted') }}
  when: not uninstall is defined
  become: yes
