---

- name: restart activemq
  action: service
    name=activemq
    state=restarted
  become: yes

- name: restart opencast
  action: service_facts
  changed_when: true
  notify: actually restart opencast

- name: actually restart opencast
  action: service
    name=opencast
    state=restarted
  when: not uninstall is defined and hostvars[inventory_hostname]['services']['opencast'] is defined
  become: yes
