---

- name: Install Java
  apt: pkg=openjdk-7-jdk update_cache=yes state=present
  sudo: yes

- name: Install Ant
  apt: pkg=ant state=present
  sudo: yes

- name: Install NFS Client
  apt: pkg=nfs-common state=present
  sudo: yes

- name: Install unzip
  apt: pkg=unzip state=present
  sudo: yes

- name: Create MH parent dir
  shell: mkdir -p {{ mh_parent_dir }}
  sudo: yes

- name: Fix MH parent dir permissions
  file: path={{mh_parent_dir}}/ owner=matterhorn group=matterhorn state=directory recurse=true
  sudo: true

- name: Checking if Red5 exists
  stat: path=/etc/init.d/red5
  register: redfivepresent

- name: Stopping Red5
  service: name=red5 state=stopped
  when: redfivepresent.stat.exists is defined and redfivepresent.stat.exists == True
  sudo: yes

- name: Create streaming parent dir
  shell: mkdir -p {{streaming_home}}

- name: Create MH shared dir
  shell: mkdir -p {{mh_work_dir}}

  #Mount NFS
- include: ../../common/tasks/nfs_mount.yml

- name: Create MH streams dir
  shell: mkdir -p {{mh_streaming_dir}}

- name: Downloading Red5
  get_url: url=http://red5.org/downloads/red5/1_0/red5-1.0.0.tar.gz
           dest={{streaming_home}}/red5-1.0.0.tar.gz
           force=no
           mode=0644

- name: Unzipping Red5
  shell: tar xzf red5-1.0.0.tar.gz
         chdir={{streaming_home}}
         creates=red5-1.0.0-build-jenkins-red5-226

- name: Symlinking Red5
  shell: ln -s red5-1.0.0-build-jenkins-red5-226 red5
         chdir={{streaming_home}}
         creates={{red5_home}}

- name: Downloading Matterhorn streaming components
  get_url: url=https://bitbucket.org/opencast-community/matterhorn-engage-streaming/get/master.tar.gz
           dest={{streaming_home}}/matterhorn-streaming-master.tar.gz
           force=no
           mode=0644

- name: Unzipping Matterhorn streaming components5
  shell: tar xzf matterhorn-streaming-master.tar.gz
         chdir={{streaming_home}}
         creates=opencast-community-matterhorn-engage-streaming-*

- name: Symlinking Matterhorn streaming components
  shell: ln -s opencast-community-matterhorn-engage-streaming-* matterhorn-engage-streaming
         chdir={{streaming_home}}
         creates=matterhorn-engage-streaming

- name: Building Matterhorn streaming application
  shell: ant clean war
         chdir={{streaming_home}}/matterhorn-engage-streaming/for-1.0-and-newer-red5
  environment:
    RED5_HOME: "{{red5_home}}"

- name: Clearing any Red5 mounts
# The mount module does not seem to work for *umounting* things...
#  mount: name={{red5_home}}/webapps/matterhorn/streams src={{mh_streaming_dir}} fstype=none state=absent fstype=none
  command: umount {{red5_home}}/webapps/matterhorn/streams
  ignore_errors: yes
  sudo: yes

- name: Cleaning out any old installs
  shell: rm -rf {{red5_home}}/webapps/matterhorn

- name: Applying Matterhorn streaming application to Red5
  shell: unzip matterhorn-engage-streaming/for-1.0-and-newer-red5/dist/*.war -d {{red5_home}}/webapps/matterhorn
         chdir={{streaming_home}}
         creates={{red5_home}}/webapps/matterhorn

- name: Setup Red5 mounts
  mount: name={{red5_home}}/webapps/matterhorn/streams src={{mh_streaming_dir}} fstype=none state=mounted opts=bind
  sudo: yes

- name: Configure red5 init script
  template: src=red5 dest=/etc/init.d/red5
  sudo: yes

- name: Fixing init script permissions
  shell: chmod a+x /etc/init.d/red5
  sudo: yes

- name: Setting Red5 to start on boot
  service: name=red5 state=started enabled=yes
  sudo: yes
