---

- include: ../../common/tasks/create_tools_bin.yml

- name: Installing Tesseract
  apt: pkg=tesseract-ocr state=present
  sudo: yes

- name: Installing Tesseract German recognition engine
  apt: pkg=tesseract-ocr-deu state=present
  sudo: yes

- name: Installing Tesseract French recognition engine
  apt: pkg=tesseract-ocr-fra state=present
  sudo: yes

- name: Installing Tesseract Spanish recognition engine
  apt: pkg=tesseract-ocr-spa state=present
  sudo: yes
