---

- name: Install NFS server
  apt: pkg=nfs-kernel-server state=present
  sudo: yes

- name: Install NFS server
  apt: pkg=mysql-server state=present
  sudo: yes

- name: Attempting to create DB - may fail is provided user does not have CREATE DATABASE permissions
  shell: mysql -u root -e "CREATE DATABASE matterhorn CHARACTER SET utf8 COLLATE utf8_general_ci"
  ignore_errors: yes

  #Build the system
- include: tasks/build_mh.yml

- name: Start Matterhorn
  service: name=matterhorn state=restarted enabled=yes
