---

  #Mount NFS
- include: ../../common/tasks/nfs_mount.yml

  #Build the system
- include: ../../common/tasks/build_mh.yml

- name: Reconfigure service registry
  template: src=org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImpl.properties dest={{mh_base_dir}}/etc/services/

- name: Downloading ActiveMQ
  get_url: url=http://archive.apache.org/dist/activemq/5.11.0/apache-activemq-5.11.0-bin.tar.gz
           dest={{mh_tools_dir}}/apache-activemq-5.11.0-bin.tar.gz
           force=no
           mode=0644

- name: Unzipping ActiveMQ
  unarchive: src=apache-activemq-5.11.0-bin.tar.gz dest={{mh_tools_dir}}/apache-activemq-5.11.0
         copy=no
         chdir={{mh_tools_dir}}
         creates={{mh_tools_dir}}/apache-activemq-5.11.0

- name: Configuring ActiveMQ user
  shell: sed -i 's/^ACTIVEMQ_USER=""/ACTIVEMQ_USER="{{matterhorn_user}}"/' {{mh_tools_dir}}/apache-activemq-5.11.0/bin/env

- name: Configuring ActiveMQ group
  shell: echo 'ACTIVEMQ_GROUP="{{matterhorn_user}}"' >> {{mh_tools_dir}}/apache-activemq-5.11.0/bin/env

- name: Configuring ActiveMQ home location
  shell: echo 'ACTIVEMQ_HOME="{{mh_tools_dir}}/apache-activemq-5.11.0/"' >> {{mh_tools_dir}}/apache-activemq-5.11.0/bin/env

- name: Creating ActiveMQ data directory
  shell: mkdir -p {{mh_tools_dir}}/apache-activemq-data
  sudo: yes

- name: Verifying ActiveMQ directory permissions
  shell: chown {{matterhorn_user}}:{{matterhorn_user}} {{mh_tools_dir}}/apache-activemq-data

- name: Configuring ActiveMQ data location
  shell: echo 'ACTIVEMQ_DATA="{{mh_tools_dir}}/apache-activemq-data"' >> {{mh_tools_dir}}/apache-activemq-5.11.0/bin/env

- name: Copying ActiveMQ global variables
  shell: cp -rv {{mh_tools_dir}}/apache-activemq-5.11.0/bin/env /etc/default/activemq
  sudo: yes

- name: Applying ActiveMQ configuration
  shell: cp -rv {{mh_base_dir}}/docs/scripts/activemq/activemq.xml {{mh_tools_dir}}/apache-activemq-5.11.0/conf/

- name: Applying ActiveMQ init script
  shell: cp -rv {{mh_base_dir}}/docs/scripts/activemq/activemq.init /etc/init.d/activemq

- name: Copying manual ActiveMQ start/stop scripts
  shell: cp -rv {{mh_base_dir}}/docs/scripts/activemq/activemqstart.sh {{mh_base_dir}}/docs/scripts/activemq/activemqstop.sh {{mh_tools_bin}}

- name: Restarting ActiveMQ
  service: name=activemq state=started enabled=yes
  sudo: yes
