---

  #Mount NFS
- include: ../../common/tasks/nfs_mount.yml

  #Build the system
- include: ../../common/tasks/build_mh.yml

- name: Reconfigure service registry
  template: src=org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImpl.properties dest={{mh_base_dir}}/etc/services/
