---

  #Mount NFS
- include: ../../common/tasks/nfs_mount.yml

  #Build the system
- include: ../../common/tasks/build_mh.yml

- name: Reconfigure service registry
  template: src=org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImpl.properties dest={{mh_base_dir}}/etc/services/

- name: Downloading ActiveMQ
  get_url: url=http://archive.apache.org/dist/activemq/5.11.0/apache-activemq-5.11.0-bin.tar.gz
           dest={{mh_tools_dir}}/apache-activemq-5.11.0-bin.tar.gz
           force=no
           mode=0644

- name: Unzipping ActiveMQ
  unarchive: src=apache-activemq-5.11.0-bin.tar.gz dest={{mh_tools_dir}}/apache-activemq-5.11.0
         copy=no
         chdir={{mh_tools_dir}}
         creates=apache-activemq-5.11.0

- name: Applying ActiveMQ configuration
  shell: cp -rv {{mh_base_dir}}/docs/scripts/activemq/activemq.xml {{mh_tools_dir}}/apache-activemq-5.11.0/conf/

- name: Applying ActiveMQ init script
  shell: cp -rv {{mh_base_dir}}/docs/scripts/activemq/activemq.init /etc/init.d/activemq

- name: Copying manual ActiveMQ start/stop scripts
  shell: cp -rv {{mh_base_dir}}/docs/scripts/activemq/activemqstart.sh {{mh_base_dir}}/docs/scripts/activemq/activemqstop.sh {{mh_tools_bin}}

- name: Restarting ActiveMQ
  service: name=activemq state=started enabled=yes
  sudo: yes
