---

- name: Checking if Solr exists
  stat: path=/etc/init.d/solr
  register: solrpresent

- name: Install httplib2
  apt: pkg=python-httplib2 state=present
  when: solrpresent.stat.exists is defined and solrpresent.stat.exists == True
  sudo: yes

- name: Starting Solr
  service: name=solr state=restarted
  when: solrpresent.stat.exists is defined and solrpresent.stat.exists == True
  sudo: yes

- name: Waiting on Solr to be available
  when: solrpresent.stat.exists is defined and solrpresent.stat.exists == True
  wait_for: port={{solr_port}}

- name: Waiting until Solr is alive
  when: solrpresent.stat.exists is defined and solrpresent.stat.exists == True
  uri: url={{engage_solr_index}} return_content=true
  register: response
  until: response.content is defined and response.content | search("Welcome to Solr!")
  delay: 10
  retries: 12
