---

- name: Install Java
  apt: pkg=openjdk-7-jdk update_cache=yes state=present
  sudo: yes

- name: Install Git
  apt: pkg=git-core state=present
  sudo: yes

- name: Create MH parent dir
  shell: mkdir -p {{ mh_parent_dir }}
  sudo: yes

- name: Fix MH parent dir permissions
  file: path={{mh_parent_dir}}/ owner=matterhorn group=matterhorn state=directory recurse=true
  sudo: true

- name: Create MH shared dir
  shell: mkdir -p {{mh_work_dir}}

#- name: Download Maven
#  get_url: url=http://archive.apache.org/dist/maven/binaries/apache-maven-{{mvn_version}}-bin.tar.gz
#           dest={{mh_parent_dir}}
#           mode=0644

#- name: Install Maven
#  shell: tar xvzf apache-maven-{{mvn_version}}-bin.tar.gz 
#         chdir={{mh_parent_dir}}

- name: Install Maven
  apt: pkg=maven state=present
  sudo: yes

#From https://coderwall.com/p/ynvi0q
#- name: add Maven to path
#  lineinfile: dest=/etc/environment
#              state=present
#              backrefs=yes
#              regexp='PATH=(["]*)((?!.*?{{mh_parent_dir}}\/apache-maven-{{mvn_version}}\/bin).*?)(["]*)$'
#              line="PATH=\1\2:{{mh_parent_dir}}/apache-maven-{{mvn_version}}/bin\3"
#  sudo: yes

- include: ../../common/tasks/clone_mh.yml

- name: Check if Matterhorn is symlinked
  command: test -e felix
           chdir={{mh_parent_dir}}
  ignore_errors: True
  register: felix_done

- name: Symlinking Matterhorn
  shell: ln -s matterhorn felix
         chdir={{mh_parent_dir}}
  ignore_errors: True
  when: felix_done.rc != 0
