---

- name: Install Java
  apt: pkg=openjdk-7-jdk state=present
  sudo: yes

- name: Install Git
  apt: pkg=git-core state=present
  sudo: yes

- name: Install NFS client
  apt: pkg=nfs-common state=present
  sudo: yes

- name: Create MH parent dir
  shell: mkdir -p {{mh_parent_dir}}
  sudo: yes

- name: Fix MH parent dir permissions
  file: path={{mh_parent_dir}}/ owner=matterhorn group=matterhorn state=directory recurse=true
  sudo: true

- name: Create MH shared dir
  shell: mkdir -p {{mh_parent_dir}}/shared

- name: Download Maven
  get_url: url=http://archive.apache.org/dist/maven/binaries/apache-maven-{{mvn_version}}-bin.tar.gz
           dest={{mh_parent_dir}}
           mode=0644

- name: Install Maven
  shell: tar xvzf apache-maven-{{mvn_version}}-bin.tar.gz 
         chdir={{mh_parent_dir}}

#From https://coderwall.com/p/ynvi0q
- name: add {{mh_parent_dir}}/ to path
  lineinfile: dest=/etc/environment
              state=present
              backrefs=yes
              regexp='PATH=(["]*)((?!.*?{{mh_parent_dir}}\/apache-maven-{{mvn_version}}\/bin).*?)(["]*)$'
              line="PATH=\1\2:{{mh_parent_dir}}/apache-maven-{{mvn_version}}/bin\3"
  sudo: yes

- name: Checkout Matterhorn
  git: repo={{git_repo_location}}
       dest={{mh_base_dir}}
       update=yes
#  This is busted, go figure
#       version=origin/develop

- name: Checkout correct version of Matterhorn
  shell: git checkout develop
         chdir={{mh_base_dir}}

- name: Configure init scripts
  template: src=etc-matterhorn-service.conf dest={{mh_base_dir}}/docs/scripts/init/new/

- name: Install the init scripts
  shell: ./install.sh
         chdir={{mh_base_dir}}/docs/scripts/init/new/
  sudo: yes

- name: Configure config.properties
  template: src=config.properties dest={{mh_base_dir}}/etc/

- name: Configure organization profile
  template: src=org.opencastproject.organization-mh_default_org.cfg dest={{mh_base_dir}}/etc/load/
  
- name: Install 3rd party tools
  shell: ./do-all
         chdir={{mh_base_dir}}/docs/scripts/3rd_party
  sudo: yes
