---

- name: Install httplib2
  apt: pkg=python-httplib2 state=present
  sudo: yes

- name: Setting pyCA to start on boot
  service: name=pyca state=started enabled=yes
  sudo: yes

- name: Waiting on pyCA to be available
  wait_for: port=8080

- name: Waiting until Matterhorn page contains `Welcome to Matterhorn` string
  uri: url=http://{{ inventory_hostname }} return_content=true
  register: response
  until: response.content is defined and response.content | search("Welcome to Matterhorn")
  delay: 10
  retries: 12

