---

- name: Ensuring sudo is present
  apt: pkg=sudo state=present

- name: Creating the Matterhorn user
  user: name={{matterhorn_user}} group={{matterhorn_group}} groups=sudo state=present

- name: Pushing SSH configs
  copy: src=../../../group_vars/ssh/ dest=/home/{{matterhorn_user}}/.ssh owner={{matterhorn_user}} group={{matterhorn_group}} mode=600
