---
- include: checkout_mh.yml

- include: clean_mh.yml

- name: Fix MH parent dir permissions
  file: path={{mh_parent_dir}}/ owner="{{matterhorn_user}}" group="{{matterhorn_group}}" state=directory recurse=true
  sudo: true

- name: Build with tests
  shell: MAVEN_OPTS="{{maven_opts}}" {{mh_tools_bin}}/mvn clean install -DdeployTo="{{mh_base_dir}}" -P "{{mh_build_profile}}" -Dcheckstyles.skip="{{checkstyle_skip}}"
         chdir={{mh_base_dir}}
  when: not skip_tests and do_build

- name: Build without tests
  shell: MAVEN_OPTS="{{maven_opts}}" {{mh_tools_bin}}/mvn clean install -DdeployTo="{{mh_base_dir}}" -P "{{mh_build_profile}}" -Dcheckstyles.skip="{{checkstyle_skip}}" -DskipTests
         chdir={{mh_base_dir}}
  when: skip_tests and do_build
