---
- include: checkout_mh.yml

- include: clean_mh.yml

- name: Build
  shell: mvn clean install -Dmaven.repo.local={{mh_work_dir}}/.m2/repository -DdeployTo={{mh_base_dir}} -P {{mh_build_profile}}
         chdir={{mh_base_dir}}
