---
- include: checkout_mh.yml

- include: clean_mh.yml

- name: Build
  shell: mvn clean install -Dmaven.repo.local={{m2_repo}} -DdeployTo={{mh_base_dir}} -P {{mh_build_profile}}
         chdir={{mh_base_dir}}
