---
- include: checkout_mh.yml

- include: clean_mh.yml

- name: Fix MH parent dir permissions
  file: path={{mh_parent_dir}}/ owner="{{matterhorn_user}}" group="{{matterhorn_user}}" state=directory recurse=true
  sudo: true

- name: Build
  shell: MAVEN_OPTS="{{maven_opts}}" mvn clean install -DdeployTo={{mh_base_dir}} -P {{mh_build_profile}} -Dcheckstyles.skip={{checkstyle_skip}}
         chdir={{mh_base_dir}}
