---
- include: checkout_mh.yml

- include: clean_mh.yml

- name: Fix MH parent dir permissions
  file: path={{mh_parent_dir}}/ owner="{{matterhorn_user}}" group="{{matterhorn_user}}" state=directory recurse=true
  sudo: true

- name: Build
  shell: MAVEN_OPTS="-Xms256m -Xmx512m -XX:PermSize=64m -XX:MaxPermSize=128m" mvn clean install -Dmaven.repo.local={{m2_repo}} -DdeployTo={{mh_base_dir}} -P {{mh_build_profile}}
         chdir={{mh_base_dir}}
