---
- include: checkout_mh.yml

- include: clean_mh.yml

- name: Build
  shell: MAVEN_OPTS="-Xms256m -Xmx512m -XX:PermSize=64m -XX:MaxPermSize=128m" mvn clean install -Dmaven.repo.local={{m2_repo}} -DdeployTo={{mh_base_dir}} -P {{mh_build_profile}}
         chdir={{mh_base_dir}}
