---

- name: Clean existing build 1/2
  file: path={{mh_base_dir}}/lib/ext state=absent

- name: Clean existing build 2/2
  file: path={{mh_base_dir}}/lib/matterhorn state=absent

- name: Clean Matterhorn log
  file: path={{mh_base_dir}}/logs state=absent

- name: Create logging directory
  file: path={{mh_base_dir}}/logs state=directory owner={{matterhorn_user}} group={{matterhorn_group}}
