---

- name: Ensuring MySQL is installed
  apt: pkg=mysql-server update_cache=yes state=present
  sudo: yes

- name: Ensuring Python MySQLdb module is installed
  apt: pkg=python-mysqldb state=present
  sudo: yes

- name: MySQL ROOT Dumping DB
  mysql_db: name={{db_schema}} login_user=root login_password= state=absent
  ignore_errors: yes

- name: MySQL ROOT Creating DB
  mysql_db: name={{db_schema}} login_user=root login_password= state=present encoding="utf8" collation="utf8_general_ci"

- name: Checking if DDL exists
  stat: path={{db_schema_location}}
  when: not db_ddl

- name: Applying MySQL schema
  mysql_db: name={{db_schema}} login_user=root login_password= state=import target={{db_schema_location}}
  when: not db_ddl
