---

- name: MySQL ROOT Dumping DB
  mysql_db: name={{db_schema}} login_user=root login_password= state=absent
  ignore_errors: yes

- name: MySQL ROOT Creating DB
  mysql_db: name={{db_schema}} login_user=root login_password= state=present encoding="utf8" collation="utf8_general_ci"

- name: Applying MySQL schema
  mysql_db: name={{db_schema}} login_user=root login_password= state=import target={{mh_base_dir}}/docs/scripts/ddl/mysql5.sql
