---

- include: wipe_db.yml

- name: MySQL ROOT Creating DB
  mysql_db: name={{db_schema}} login_user=root login_password= state=present encoding="utf8" collation="utf8_general_ci"

- name: Checking if DDL exists
  stat: path={{db_schema_location}}
  register: dbschemapresent
  when: not db_ddl

- name: Applying MySQL schema
  mysql_db: name={{db_schema}} login_user=root login_password= state=import target={{db_schema_location}}
  when: not db_ddl and dbschemapresent.stat.exists is defined and dbschemapresent.stat.exists == True
