---

- name: Clean existing build 1/2
  file: path={{mh_base_dir}}/lib/ext state=absent

- name: Clean existing build 2/2
  file: path={{mh_base_dir}}/lib/matterhorn state=absent

- include: clean_mh_logs.yml
