---

- name: Clean existing build 1/2
  file: path={{mh_base_dir}}/lib/ext state=absent
  when: do_build

- name: Clean existing build 2/2
  file: path={{mh_base_dir}}/lib/matterhorn state=absent
  when: do_build

- include: clean_mh_logs.yml
