---

- name: Create MH parent dir
  file: path={{ mh_parent_dir }} owner={{matterhorn_user}} group={{matterhorn_group}} state=directory
  sudo: yes

- name: Pushing SSH configs
  copy: src=../../../group_vars/ssh/ dest=/home/{{matterhorn_user}}/.ssh mode=600

- name: Ensuring Git is installed
  apt: pkg=git state=present
  sudo: yes

- name: Checkout Matterhorn
  git: repo={{git_repo_location}}
       dest={{mh_base_dir}}
       update=yes
       version={{mh_version}}
