---

#We're deliberately creating a the bin directory here since it also creates the tools dir
- name: Creating Matterhorn tools directory
  file: path={{mh_tools_bin}} owner={{matterhorn_user}} group={{matterhorn_group}} state=directory
