---

- name: Delete Matterhorn data
  file: path={{mh_parent_dir}}/work/ state=absent
  when: "'fileserver' in group_names"

- name: Recreate work directory
  file: path={{mh_parent_dir}}/work/ owner={{matterhorn_user}} group={{matterhorn_group}} state=directory
  when: "'fileserver' in group_names"

- name: Clean Matterhorn log
  file: path={{mh_base_dir}}/logs state=absent

- name: Create logging directory
  file: path={{mh_base_dir}}/logs state=directory owner={{matterhorn_user}} group={{matterhorn_group}}
  sudo: yes
