---

- name: Delete ActiveMQ data directory
  file: path={{activemq_data_dir}} state=absent

- name: Recreate ActiveMQ data directory
  file: path={{activemq_data_dir}} state=directory owner={{activemq_user}} group={{activemq_group}}
  sudo: yes

- name: Delete ActiveMQ log directory
  file: path={{activemq_log_dir}} state=absent

- name: Recreate ActiveMQ log directory
  file: path={{activemq_log_dir}} state=directory owner={{activemq_user}} group={{activemq_group}}
  sudo: yes

