---

- name: Delete Matterhorn data
  file: path={{mh_parent_dir}}/work/ state=absent
  when: "'fileserver' in group_names"
  sudo: yes

- name: Recreate work directory
  file: path={{mh_parent_dir}}/work/ owner={{matterhorn_user}} group={{matterhorn_group}} state=directory
  when: "'fileserver' in group_names"
  sudo: yes

- include: clean_mh_logs.yml
