---

- name: Checking if Solr exists
  stat: path=/etc/init.d/solr
  register: solrpresent

- name: Stopping Solr
  service: name=solr state=stopped
  sudo: yes
  when: solrpresent.stat.exists is defined and solrpresent.stat.exists == True
