---

- include: ../../solr-stop/tasks/main.yml

- name: Stop and disable Solr
  service: name=solr state=stopped enabled=no
  sudo: yes
  when: solrpresent.stat.exists is defined and solrpresent.stat.exists == True

- name: Removing Solr init script
  file: path=/etc/init.d/solr state=absent
  sudo: yes
  when: solrpresent.stat.exists is defined and solrpresent.stat.exists == True

- name: Wipe Solr root directory
  file: path={{tomcat_dir}} state=absent
  sudo: yes
