---

- name: Dropping any existing Opencast database schema
  mysql_db:
    state: absent
    name: "{{ oc_db_schema }}"
  become: yes
  ignore_errors: yes
  tags:
    - never
    - reset

  # Try creating DB ourselves so can register change
- name: Create the Opencast database
  mysql_db:
    name: "{{ oc_db_schema }}"
    state: present
  register: oc_database_created
  become: yes

- name: Copying schema to database server
  copy:
    src: mysql5.sql
    dest: /tmp/mysql5.sql
    force: yes
  tags:
    - reset
  when: oc_database_created.changed and not uninstall is defined

- name: Importing Opencast database schema
  mysql_db:
    state: import
    name: "{{ oc_db_schema }}"
    target: "/tmp/mysql5.sql"
  tags:
    - reset
  when: oc_database_created.changed and not uninstall is defined
  become: yes
